[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'php82Extensions.intl', 'php82Extensions.gd', 'php82Extensions.bcmath', 'php82Extensions.zip', 'php82Extensions.pdo_mysql', 'nginx', 'nodejs']

[phases.build]
cmds = ['composer install --no-dev --optimize-autoloader', 'npm install', 'npm run build']

[start]
cmd = 'php-fpm -D && nginx -g "daemon off;"'
